name: Build Doxygen Documentation
on: push

jobs:
  docummentation:
    runs-on: ubuntu-latest
    steps:
      - name: Install Graphviz and Doxygen
        run: |
          sudo apt-add-repository universe
          sudo apt-get update
          sudo apt-get install graphviz
          sudo apt-get install doxygen

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate documentation
        run: doxygen Doxyfile
