name: Build Doxygen Documentation
on: push

jobs:
  install-doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Install Doxygen
        run: |
          sudo apt-add-repository universe
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Generate Doxyfile
        run: |
          doxygen -g Doxyfile
          cat Doxyfile

#      - name: Check out repository
#        uses: actions/checkout@v4

#      - name: Run Doxygen
#        run: doxygen Doxyfile
